<?php

namespace Database\Seeders\master;

use Illuminate\Database\Seeder;
use App\Models\NavigationModule;

class NavigationModuleSeeder extends Seeder
{
    public function run()
    {
        $modules = [
            [
                'navigation_id' => 1,
                'permission_id' => 1,
                'name' => 'Admin Dashboard',
                'icon' => 'SquareTerminal',
                'url' => '/dashboard',
                'slug' => 'dashboard',
                'ref_id' => null,
                'order_number'=> 1,
                'status' => 1,
                'created_by' => 1,
            ],
            //Users
            [
                'navigation_id' => 1,
                'permission_id' => 2,
                'name' => 'User List',
                'icon' => 'Users',
                'url' => '/users',
                'slug' => 'users.index',
                'ref_id' => null,
                'order_number'=> 2,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 1,
                'permission_id' => 3,
                'name' => 'Create User',
                'icon' => 'UserPlus',
                'url' => '/users/create',
                'slug' => 'users.create',
                'ref_id' => 2,
                'order_number'=> 3,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 1,
                'permission_id' => 4,
                'name' => 'Edit User',
                'icon' => 'Pencil',
                'color' => 'blue',
                'url' => '/users/{id}/edit',
                'slug' => 'users.edit',
                'ref_id' => 2,
                'order_number'=> 4,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 1,
                'permission_id' => 5,
                'name' => 'Delete User',
                'icon' => 'Trash2',
                'color' => 'red',
                'url' => '/users/destroy',
                'slug' => 'users.destroy',
                'ref_id' => 2,
                'order_number'=> 5,
                'status' => 1,
                'created_by' => 1,
            ],
            //roles
            [
                'navigation_id' => 1,
                'permission_id' => 6,
                'name' => 'Role List',
                'icon' => 'Lock',
                'url' => '/roles',
                'slug' => 'roles.index',
                'ref_id' => null,
                'order_number'=> 6,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 1,
                'permission_id' => 7,
                'name' => 'Create Role',
                'icon' => 'UserPlus',
                'url' => '/roles/create',
                'slug' => 'roles.create',
                'ref_id' => 6,
                'order_number'=> 7,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 1,
                'permission_id' => 8,
                'name' => 'Edit Role',
                'icon' => 'Pencil',
                'color' => 'blue',
                'url' => '/roles/{id}/edit',
                'slug' => 'roles.edit',
                'ref_id' => 6,
                'order_number'=> 8,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 1,
                'permission_id' => 9,
                'name' => 'Delete Role',
                'icon' => 'Trash2',
                'color' => 'red',
                'url' => '/roles/destroy',
                'slug' => 'roles.destroy',
                'ref_id' => 6,
                'order_number'=> 9,
                'status' => 1,
                'created_by' => 1,
            ],
            //permissions
            [
                'navigation_id' => 1,
                'permission_id' => 10,
                'name' => 'Permission List',
                'icon' => 'Key',
                'url' => '/permissions',
                'slug' => 'permissions.index',
                'ref_id' => null,
                'order_number'=> 10,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 1,
                'permission_id' => 11,
                'name' => 'Create Permission',
                'icon' => 'UserPlus',
                'url' => '/permissions/create',
                'slug' => 'permissions.create',
                'ref_id' => 10,
                'order_number'=> 11,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 1,
                'permission_id' => 12,
                'name' => 'Edit Permission',
                'icon' => 'Pencil',
                'color' => 'blue',
                'url' => '/permissions/{id}/edit',
                'slug' => 'permissions.edit',
                'ref_id' => 10,
                'order_number'=> 12,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 1,
                'permission_id' => 13,
                'name' => 'Delete Permission',
                'icon' => 'Trash2',
                'color' => 'red',
                'url' => '/permissions/destroy',
                'slug' => 'permissions.destroy',
                'ref_id' => 10,
                'order_number'=> 13,
                'status' => 1,
                'created_by' => 1,
            ],
            //navigations
            [
                'navigation_id' => 1,
                'permission_id' => 14,
                'name' => 'Navigation List',
                'icon' => 'Menu',
                'url' => '/navigations',
                'slug' => 'navigations.index',
                'ref_id' => null,
                'order_number'=> 14,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 1,
                'permission_id' => 15,
                'name' => 'Create Navigation',
                'icon' => 'UserPlus',
                'url' => '/navigations/create',
                'slug' => 'navigations.create',
                'ref_id' => 14,
                'order_number'=> 15,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 1,
                'permission_id' => 16,
                'name' => 'Edit Navigation',
                'icon' => 'Pencil',
                'color' => 'blue',
                'url' => '/navigations/{id}/edit',
                'slug' => 'navigations.edit',
                'ref_id' => 14,
                'order_number'=> 16,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 1,
                'permission_id' => 17,
                'name' => 'Delete Navigation',
                'icon' => 'Trash2',
                'color' => 'red',
                'url' => '/navigations/destroy',
                'slug' => 'navigations.destroy',
                'ref_id' => 14,
                'order_number'=> 17,
                'status' => 1,
                'created_by' => 1,
            ],
            //soas
            [
                'navigation_id' => 2,
                'permission_id' => 18,
                'name' => 'Soa List',
                'icon' => 'Menu',
                'url' => '/soas',
                'slug' => 'soas.index',
                'ref_id' => null,
                'order_number'=> 18,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 2,
                'permission_id' => 19,
                'name' => 'Create Soa',
                'icon' => 'UserPlus',
                'url' => '/soas/create',
                'slug' => 'soas.create',
                'ref_id' => 18,
                'order_number'=> 19,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 2,
                'permission_id' => 20,
                'name' => 'Edit Soa',
                'icon' => 'Pencil',
                'color' => 'blue',
                'url' => '/soas/{id}/edit',
                'slug' => 'soas.edit',
                'ref_id' => 18,
                'order_number'=> 20,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 2,
                'permission_id' => 21,
                'name' => 'Delete Soa',
                'icon' => 'Trash2',
                'color' => 'red',
                'url' => '/soas/destroy',
                'slug' => 'soas.destroy',
                'ref_id' => 18,
                'order_number'=> 21,
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'navigation_id' => 2,
                'permission_id' => 22,
                'name' => 'Manage Soa File',
                'icon' => 'File',
                'color' => 'yellow',
                'url' => '/soas/{id}/manage_file',
                'slug' => 'soas.manage_file',
                'ref_id' => 18,
                'order_number'=> 22,
                'status' => 1,
                'created_by' => 1,
            ],
        ];

        try {
            foreach ($modules as $module) {
                NavigationModule::firstOrCreate(
                    [
                        'navigation_id' => $module['navigation_id'],
                        'name' => $module['name'],
                    ],
                    $module
                );
            }
        } catch (\Exception $e) {
            throw $e;
        }
    }
}
